namespace iPodCommander;

// AUTO-GENERATED from the localization workflow (2026-06-20). Merged into LocHu.Map via TryAdd, so the
// hand-curated entries in LocHu.cs win and duplicate keys here are harmless. Edit translations there.
internal static partial class LocHu
{
    internal static readonly (string En, string Hu)[] Generated =
    {
        ("Write failed (a backup was kept as iTunesDB.bak):\n\n{0}", "A írás sikertelen (biztonsági mentés megmaradt iTunesDB.bak néven):\n\n{0}"),
        ("Playlist order updated.", "A lejátszási lista sorrendje frissítve."),
        ("The file for this item can't be found, so it can't be played.", "Ennek az elemnek a fájlja nem található, ezért nem játszható le."),
        ("Play", "Lejátszás"),
        ("Play next   ({0})", "Lejátszás következőként   ({0})"),
        ("Play next", "Lejátszás következőként"),
        ("Add to queue   ({0})", "Hozzáadás a sorhoz   ({0})"),
        ("Add to queue", "Hozzáadás a sorhoz"),
        ("Select a song to edit.", "Válassz egy dalt a szerkesztéshez."),
        ("Saving song info", "Daladatok mentése"),
        ("Updating “{0}”", "„{0}” frissítése"),
        ("Updating {0} of {1} songs…", "{0}/{1} dal frissítése…"),
        ("Done", "Kész"),
        ("Saving failed (a backup was kept as iTunesDB.bak):\n\n{0}", "A mentés sikertelen (biztonsági mentés megmaradt iTunesDB.bak néven):\n\n{0}"),
        ("Updated “{0}”.", "„{0}” frissítve."),
        ("Updated {0} songs.", "{0} dal frissítve."),
        ("Select one or more songs to copy to the PC.", "Válassz ki egy vagy több dalt a gépre másoláshoz."),
        ("Copy {0} song(s) from the iPod into this folder", "{0} dal másolása az iPodról ebbe a mappába"),
        ("Copying songs to your PC", "Dalok másolása a gépedre"),
        ("Copying {0} of {1}   ·   {2}", "Másolás: {0}/{1}   ·   {2}"),
        ("Stopped — copied {0} song(s).", "Leállítva — {0} dal másolva."),
        ("Copied {0} song(s) to:\n{1}", "{0} dal ide másolva:\n{1}"),
        ("\n\n{0} had no file on the iPod (skipped).", "\n\n{0} elemhez nem volt fájl az iPodon (kihagyva)."),
        ("\n\n{0} failed:\n• ", "\n\n{0} sikertelen:\n• "),
        ("Copy to PC", "Másolás a gépre"),
        ("Detection error: {0}", "Észlelési hiba: {0}"),
        ("{0} iPod connected.", "{0} iPod csatlakoztatva."),
        ("{0} iPods connected.", "{0} iPod csatlakoztatva."),
        ("Select the iPod's drive root (the folder that contains iPod_Control)", "Válaszd ki az iPod meghajtójának gyökerét (az iPod_Control mappát tartalmazó mappa)"),
        ("That folder has no iPod_Control directory, so it isn't an iPod root.", "Ebben a mappában nincs iPod_Control könyvtár, így nem iPod-gyökér."),
        ("Failed to read iTunesDB: {0}", "Az iTunesDB beolvasása sikertelen: {0}"),
        ("Could not read this iPod's database:\n\n{0}", "Nem sikerült beolvasni az iPod adatbázisát:\n\n{0}"),
        ("Looking for your iPod…", "Az iPod keresése…"),
        ("Scanning for a connected iPod.", "Csatlakoztatott iPod keresése."),
        ("No iPod connected", "Nincs csatlakoztatott iPod"),
        ("Plug in your iPod — Mixtape detects it automatically. Or use Open folder. A Mac-formatted (HFS+) iPod isn't readable on Windows.", "Csatlakoztasd az iPodot — a Mixtape automatikusan felismeri. Vagy használd a Mappa megnyitása lehetőséget. A Mac-formátumú (HFS+) iPod Windows alatt nem olvasható."),
        ("This iPod isn't on a drive letter, so it can't be ejected from here. Use Windows' “Safely Remove Hardware”.", "Ez az iPod nincs meghajtóbetűjelen, így innen nem lehet leválasztani. Használd a Windows „Hardver biztonságos eltávolítása” funkcióját."),
        ("Eject", "Leválasztás"),
        ("Ejected — safe to unplug your iPod.", "Leválasztva — az iPod biztonságosan kihúzható."),
        ("Couldn't eject the iPod:\n\n{0}", "Nem sikerült leválasztani az iPodot:\n\n{0}"),
        ("Untitled", "Névtelen"),
        ("Album", "Album"),
        ("ALBUM", "ALBUM"),
        ("ARTIST", "ELŐADÓ"),
        ("Unknown Artist", "Ismeretlen előadó"),
        ("Unknown Album", "Ismeretlen album"),
        ("Repeat One is on — queue advances on Next", "Egy ismétlése bekapcsolva — a sor a Következővel lép tovább"),
        ("No iPod is connected.", "Nincs csatlakoztatott iPod."),
        ("This iPod is read-only.", "Ez az iPod csak olvasható."),
        ("This iPod doesn't have a colour screen, so it can't store photos.", "Ennek az iPodnak nincs színes kijelzője, így nem tud fényképeket tárolni."),
        ("Photos can't be written to this iPod.", "Erre az iPodra nem lehet fényképeket írni."),
        ("Why is this greyed out?", "Miért szürke ez?"),
        ("Plug in your iPod (in disk mode) and press Refresh, or use Open folder to point at its drive. A Mac-formatted (HFS+) iPod can't be read on Windows.", "Csatlakoztasd az iPodot (lemez módban) és nyomd meg a Frissítést, vagy a Mappa megnyitásával mutass a meghajtójára. A Mac-formátumú (HFS+) iPod Windows alatt nem olvasható."),
        ("Photos work on the iPod photo, 5G (video), Classic, and nano 3G and later.", "A fényképek az iPod photo, 5G (video), Classic, valamint a nano 3G és újabb modelleken működnek."),
        ("Photos can't be written to this iPod right now.", "Erre az iPodra jelenleg nem lehet fényképeket írni."),
        ("Check the iPod isn't read-only on its device page, then try again.", "Ellenőrizd az eszköz oldalán, hogy az iPod nem csak olvasható, majd próbáld újra."),
        ("Open this iPod's device page and click “Read device ID” — a safe, read-only query that reads the iPod's hardware ID (the same thing iTunes does) so music can be written.", "Nyisd meg az iPod eszköz oldalát, és kattints az „Eszközazonosító beolvasása” gombra — ez egy biztonságos, csak olvasó lekérdezés, amely beolvassa az iPod hardverazonosítóját (ugyanúgy, mint az iTunes), hogy zenét lehessen rá írni."),
        ("Mixtape's signature for this iPod didn't match the one already on it, so writing stays disabled to avoid corrupting its library. Open the device page and use “Save report…” so this can be looked into.", "A Mixtape aláírása ehhez az iPodhoz nem egyezett a rajta lévővel, ezért az írás letiltva marad, hogy ne sérüljön a könyvtár. Nyisd meg az eszköz oldalát, és használd a „Jelentés mentése…” lehetőséget, hogy ezt ki lehessen vizsgálni."),
        ("This iPod's signature (hash72, used by the nano 5G / Touch) can't be reproduced yet, so writing isn't possible. You can still browse, play, and copy music off the iPod.", "Ennek az iPodnak az aláírása (hash72, a nano 5G / Touch használja) egyelőre nem reprodukálható, így az írás nem lehetséges. Továbbra is böngészhetsz, lejátszhatsz és lemásolhatsz zenét az iPodról."),
        ("This iPod uses the experimental hashAB signature (nano 6G/7G), which isn't enabled yet. Browsing and copying off still work.", "Ez az iPod a kísérleti hashAB aláírást használja (nano 6G/7G), amely még nincs engedélyezve. A böngészés és a lemásolás továbbra is működik."),
        ("See the device page for details on this iPod's signature.", "Az iPod aláírásának részleteiért lásd az eszköz oldalát."),
        ("\n\nOpen the device page now?", "\n\nMegnyitod most az eszköz oldalát?"),
        ("{0} selected   ·   {1}", "{0} kijelölve   ·   {1}"),
        ("Cover for All songs", "Borító az Összes dalhoz"),
        ("Cover for “{0}”", "„{0}” borítója"),
        ("Choose cover…", "Borító kiválasztása…"),
        ("Read-only — {0}", "Csak olvasható — {0}"),
        ("New playlist…", "Új lejátszási lista…"),
        ("{0} of {1} used", "{0} / {1} használatban"),
        ("Connected", "Csatlakoztatva"),
        ("{0} free", "{0} szabad"),
        ("STORAGE", "TÁROLÓ"),
        ("Music", "Zene"),
        ("Video", "Videó"),
        ("Photos", "Fényképek"),
        ("Free", "Szabad"),
        ("ABOUT", "NÉVJEGY"),
        ("Model", "Modell"),
        ("Generation", "Generáció"),
        ("Capacity", "Kapacitás"),
        ("{0}  ·  {1} free", "{0}  ·  {1} szabad"),
        ("Songs", "Dalok"),
        ("Videos", "Videók"),
        ("Signature", "Aláírás"),
        ("Writable", "Írható"),
        ("Yes", "Igen"),
        ("No", "Nem"),
        ("Serial", "Sorozatszám"),
        ("FireWire GUID", "FireWire GUID"),
        ("Why read-only", "Miért csak olvasható"),
        ("Read device ID", "Eszközazonosító beolvasása"),
        ("Enable writing", "Írás engedélyezése"),
        ("Read this iPod's hardware ID directly from the device (a safe, read-only query — the same thing iTunes does) so music can be written. No iTunes needed.", "Olvasd be az iPod hardverazonosítóját közvetlenül az eszközről (biztonságos, csak olvasó lekérdezés — ugyanúgy, mint az iTunes), hogy zenét lehessen rá írni. iTunes nem szükséges."),
        ("BACKUPS", "BIZTONSÁGI MENTÉSEK"),
        ("Last automatic backup: {0}.", "Utolsó automatikus mentés: {0}."),
        ("Original database kept.", "Az eredeti adatbázis megőrizve."),
        ("No backup yet.", "Még nincs biztonsági mentés."),
        ("Restore…", "Visszaállítás…"),
        ("Automatic backup", "Automatikus mentés"),
        (" Mixtape backs up before every change and verifies the result.", " A Mixtape minden változtatás előtt biztonsági mentést készít, és ellenőrzi az eredményt."),
        ("OPTIONS", "BEÁLLÍTÁSOK"),
        ("⏏  Eject", "⏏  Leválasztás"),
        ("Safely remove", "Biztonságos eltávolítás"),
        ("Flush changes and eject so you can unplug the iPod safely.", "A változtatások kiírása és leválasztás, hogy biztonságosan kihúzhasd az iPodot."),
        ("Open Settings", "Beállítások megnyitása"),
        ("All settings", "Összes beállítás"),
        ("Appearance, library, video, photos and safety.", "Megjelenés, könyvtár, videó, fényképek és biztonság."),
        ("Show in Explorer", "Megjelenítés az Intézőben"),
        ("Files", "Fájlok"),
        ("Open the iPod's drive in File Explorer.", "Az iPod meghajtójának megnyitása a Fájlkezelőben."),
        ("Save report…", "Jelentés mentése…"),
        ("Device report", "Eszközjelentés"),
        ("Save a diagnostic file (model, signature, why it's read-only) to send for support.", "Diagnosztikai fájl mentése (modell, aláírás, miért csak olvasható), hogy elküldd támogatásért."),
        ("Rebuild artwork", "Borítók újraépítése"),
        ("Album artwork", "Albumborító"),
        ("Write cover art onto every song already on the iPod (from each file's embedded cover). Handy after copying songs from an older version.", "Borító írása minden, az iPodon már meglévő dalra (az egyes fájlokba ágyazott borítóból). Hasznos, miután régebbi verzióból másoltál dalokat."),
        ("Check library", "Könyvtár ellenőrzése"),
        ("Library Doctor", "Könyvtárdoktor"),
        ("Scan for missing files, duplicate songs and stray files left on the iPod — then fix them safely in one click.", "Hiányzó fájlok, ismétlődő dalok és az iPodon hagyott árva fájlok keresése — majd biztonságos javításuk egyetlen kattintással."),
        ("This writes album art onto every song already on the iPod, reading the cover embedded in each music file.\n\nSongs whose files have no embedded cover are left without art. Mixtape backs up the database first. Continue?", "Ez minden, az iPodon már meglévő dalra borítót ír, az egyes zenefájlokba ágyazott borítóból olvasva.\n\nAzok a dalok, amelyek fájljában nincs beágyazott borító, borító nélkül maradnak. A Mixtape először biztonsági mentést készít az adatbázisról. Folytatod?"),
        ("Rebuilding artwork…", "Borítók újraépítése…"),
        ("This iPod's artwork database can't be written safely.", "Ennek az iPodnak a borító-adatbázisa nem írható biztonságosan."),
        ("Rebuild artwork failed.", "A borítók újraépítése sikertelen."),
        ("Couldn't rebuild artwork:\n\n{0}", "Nem sikerült újraépíteni a borítókat:\n\n{0}"),
        ("Artwork rebuilt for {0} song(s).", "Borítók újraépítve {0} dalhoz."),
        ("Wrote cover art for {0} song(s).", "Borító kiírva {0} dalhoz."),
        ("\n{0} song(s) had no embedded cover in the file.", "\n{0} dal fájljában nem volt beágyazott borító."),
        ("\n\nEject the iPod, then check the Now Playing screen.", "\n\nVálaszd le az iPodot, majd ellenőrizd a Most játszott képernyőt."),
        ("Checking library…", "Könyvtár ellenőrzése…"),
        ("Couldn't scan the library:\n\n{0}", "Nem sikerült átvizsgálni a könyvtárat:\n\n{0}"),
        ("Fixing library…", "Könyvtár javítása…"),
        ("Library fix failed.", "A könyvtár javítása sikertelen."),
        ("Couldn't apply the fixes:\n\n{0}", "Nem sikerült alkalmazni a javításokat:\n\n{0}"),
        ("Library cleaned up.", "A könyvtár megtisztítva."),
        ("• Removed {0} dead entries", "• {0} halott bejegyzés eltávolítva"),
        ("• Removed {0} duplicates", "• {0} ismétlődés eltávolítva"),
        ("• Removed {0} duplicate photos", "• {0} ismétlődő fénykép eltávolítva"),
        ("• Cleared {0} stray files", "• {0} árva fájl törölve"),
        ("This saves a diagnostic text file containing your iPod's identifiers (serial number and FireWire GUID).\n\nOnly share it with someone helping you fix the app. Continue?", "Ez egy diagnosztikai szövegfájlt ment, amely az iPod azonosítóit tartalmazza (sorozatszám és FireWire GUID).\n\nCsak olyasvalakivel oszd meg, aki segít az alkalmazás javításában. Folytatod?"),
        ("Save device report", "Eszközjelentés mentése"),
        ("Text file", "Szövegfájl"),
        ("Device report saved.", "Eszközjelentés mentve."),
        ("Couldn't save the report:\n\n{0}", "Nem sikerült menteni a jelentést:\n\n{0}"),
        ("Save report", "Jelentés mentése"),
        ("This only works for an iPod mounted on a drive letter.", "Ez csak meghajtóbetűjelre csatlakoztatott iPodnál működik."),
        ("Mixtape will read this iPod's hardware ID directly from the device — a safe, read-only query (the same one iTunes uses) — and save it to the iPod so music can be written. Nothing on the iPod is changed except adding the standard device-info file.\n\nContinue?", "A Mixtape közvetlenül az eszközről olvassa be az iPod hardverazonosítóját — biztonságos, csak olvasó lekérdezéssel (ugyanazzal, amit az iTunes használ) —, és elmenti az iPodra, hogy zenét lehessen rá írni. Az iPodon semmi sem változik, csak a szokásos eszközinformációs fájl kerül hozzáadásra.\n\nFolytatod?"),
        ("Couldn't read a hardware ID from this iPod.\n\n", "Nem sikerült hardverazonosítót beolvasni erről az iPodról.\n\n"),
        ("The device didn't return a FireWire GUID.", "Az eszköz nem adott vissza FireWire GUID-ot."),
        ("\n\nYou can still use the iPod read-only (browse, play, copy music off). Use \"Save report…\" to capture details.", "\n\nAz iPodot továbbra is csak olvasható módon használhatod (böngészés, lejátszás, zene lemásolása). Használd a „Jelentés mentése…” lehetőséget a részletek rögzítéséhez."),
        ("Read the device ID ({0}), but the device-info document the iPod returned isn't in a form Mixtape can reliably re-read, so it was NOT saved to the iPod.\n\nPlease use \"Save report…\" and send it.", "Beolvasta az eszközazonosítót ({0}), de az iPod által visszaadott eszközinformációs dokumentum nincs olyan formában, amelyet a Mixtape megbízhatóan újra tud olvasni, ezért NEM került mentésre az iPodra.\n\nKérlek, használd a „Jelentés mentése…” lehetőséget, és küldd el."),
        ("Read the device ID ({0}) but couldn't save it to the iPod:\n\n{1}", "Beolvasta az eszközazonosítót ({0}), de nem sikerült elmenteni az iPodra:\n\n{1}"),
        ("Success — read device ID {0} and verified the signature against this iPod's database. Writing is now enabled.", "Sikerült — beolvasta a(z) {0} eszközazonosítót, és ellenőrizte az aláírást az iPod adatbázisához. Az írás mostantól engedélyezve van."),
        ("Read device ID {0}. Writing is now enabled.", "Beolvasta a(z) {0} eszközazonosítót. Az írás mostantól engedélyezve van."),
        ("Read the device ID ({0}), but Mixtape's hash58 signature didn't match this iPod's existing one, so writing stays disabled to avoid corrupting its database.\n\nThis iPod is the first real-world test of hash58 signing — please use \"Save report…\" and send it so the signing can be fixed.", "Beolvasta az eszközazonosítót ({0}), de a Mixtape hash58 aláírása nem egyezett az iPodon lévővel, ezért az írás letiltva marad, hogy ne sérüljön az adatbázis.\n\nEz az iPod a hash58 aláírás első valós tesztje — kérlek, használd a „Jelentés mentése…” lehetőséget, és küldd el, hogy az aláírást javítani lehessen."),
        ("Read the device ID ({0}). Writing is still disabled — see the reason on this page.", "Beolvasta az eszközazonosítót ({0}). Az írás továbbra is letiltva — az okot lásd ezen az oldalon."),
        ("No database backup was found on this iPod yet.", "Ezen az iPodon még nem található adatbázis biztonsági mentés."),
        ("Restore", "Visszaállítás"),
        ("the state before the last change (iTunesDB.bak)", "az utolsó változtatás előtti állapotot (iTunesDB.bak)"),
        ("the original database from before Mixtape first wrote to it", "az eredeti adatbázist abból az időből, mielőtt a Mixtape először írt rá"),
        ("Restore {0}?\n\nThe current database will be replaced.", "Visszaállítod ezt: {0}?\n\nA jelenlegi adatbázis felül lesz írva."),
        ("Restore database", "Adatbázis visszaállítása"),
        ("Restore failed:\n\n{0}", "A visszaállítás sikertelen:\n\n{0}"),
        ("Database restored.", "Az adatbázis visszaállítva."),
        ("Today", "Ma"),
        ("Yesterday", "Tegnap"),
        ("{0} selected   ·   {1}   ·   {2}", "{0} kijelölve   ·   {1}   ·   {2}"),
        ("{0} hr {1} min", "{0} ó {1} perc"),
        ("{0} min {1} s", "{0} perc {1} mp"),
        ("{0} s", "{0} mp"),
        ("These files are about {0}, but the iPod has only {1} free.\n\nThey might not all fit. (Converted media usually ends up smaller, so it may still work.)\n\nTry anyway?", "Ezek a fájlok körülbelül {0} méretűek, de az iPodon csak {1} szabad hely van.\n\nLehet, hogy nem fér el mind. (Az átalakított média általában kisebb lesz, így még működhet.)\n\nMégis megpróbálod?"),
        ("Not enough space?", "Nincs elég hely?"),
        ("Select music to copy onto the iPod", "Válassz zenét az iPodra másoláshoz"),
        ("Audio files", "Hangfájlok"),
        ("All files", "Minden fájl"),
        ("songs", "dal"),
        ("videos", "videó"),
        ("Some of these need converting to an iPod format (e.g. FLAC / OGG / Opus / WMA), but ffmpeg wasn't found.\n\n• Install ffmpeg (`winget install Gyan.FFmpeg`) and it's picked up automatically, or set its path in Settings ▸ Video.\n\nContinue and copy just the already-compatible files (mp3, m4a, wav, aiff)?", "Ezek közül néhányat iPod-formátumra kell alakítani (pl. FLAC / OGG / Opus / WMA), de az ffmpeg nem található.\n\n• Telepítsd az ffmpeg-et (`winget install Gyan.FFmpeg`), és automatikusan felismeri, vagy add meg az útvonalát a Beállítások ▸ Videó alatt.\n\nFolytatod, és csak a már kompatibilis fájlokat (mp3, m4a, wav, aiff) másolod?"),
        ("ffmpeg not found", "ffmpeg nem található"),
        ("Adding music to your iPod", "Zene hozzáadása az iPodhoz"),
        ("needs ffmpeg to convert — skipped.", "ffmpeg szükséges az átalakításhoz — kihagyva."),
        ("Converting {0} of {1}   ·   {2}", "Átalakítás: {0}/{1}   ·   {2}"),
        ("Converting {0} of {1}   ·   {2}%   ·   {3}", "Átalakítás: {0}/{1}   ·   {2}%   ·   {3}"),
        ("Saving the iPod database…", "Az iPod adatbázisának mentése…"),
        ("Writing the database failed (a backup was kept as iTunesDB.bak):\n\n{0}", "Az adatbázis írása sikertelen (biztonsági mentés megmaradt iTunesDB.bak néven):\n\n{0}"),
        ("Stopped — added {0} song(s).", "Leállítva — {0} dal hozzáadva."),
        ("Added {0} song(s).", "{0} dal hozzáadva."),
        ("\n\n{0} could not be added:\n• ", "\n\n{0} nem sikerült hozzáadni:\n• "),
        ("\n• …and {0} more", "\n• …és még {0}"),
        ("{0} of these {1} {2} look like they're already on your iPod:\n\n• {3}\n\nYes   —   Skip the duplicates, add only what's new   (recommended)\nNo    —   Add everything anyway (you'll get duplicates)\nCancel —  Don't add anything", "Ezek közül a(z) {1} {2} közül {0} úgy néz ki, mintha már az iPododon lenne:\n\n• {3}\n\nIgen   —   Az ismétlődések kihagyása, csak az új hozzáadása   (ajánlott)\nNem    —   Mégis mindent hozzáad (ismétlődések keletkeznek)\nMégse —  Semmit ne adjon hozzá"),
        ("Already on your iPod", "Már az iPododon van"),
        ("All {0} {1} are already on your iPod — nothing to add.", "Mind a(z) {0} {1} már az iPododon van — nincs mit hozzáadni."),
        ("Select one or more songs to delete.", "Válassz ki egy vagy több dalt a törléshez."),
        ("Delete {0} song(s) from the iPod, including the audio file(s)?\n\nThis can't be undone, but a backup of the database is kept (iTunesDB.bak).", "Törölsz {0} dalt az iPodról, a hangfájl(oka)t is beleértve?\n\nEz nem vonható vissza, de az adatbázisról biztonsági mentés készül (iTunesDB.bak)."),
        ("Delete songs", "Dalok törlése"),
        ("Deleted {0} song(s).", "{0} dal törölve."),
        ("Photos are read-only on this iPod.", "A fényképek csak olvashatók ezen az iPodon."),
        ("Add photos…", "Fényképek hozzáadása…"),
        ("Add folder…   (includes subfolders)", "Mappa hozzáadása…   (az almappákkal együtt)"),
        ("Select a folder — every photo inside it and its subfolders will be added", "Válassz mappát — minden benne és az almappáiban lévő fénykép hozzáadásra kerül"),
        ("No photos (jpg, png, …) were found in that folder or its subfolders.", "Nem található fénykép (jpg, png, …) abban a mappában vagy az almappáiban."),
        ("Add folder", "Mappa hozzáadása"),
        ("Found {0} photo(s) in “{1}” (including subfolders).\n\nAdd them all to the iPod?", "{0} fénykép található itt: „{1}” (az almappákkal együtt).\n\nMindet hozzáadod az iPodhoz?"),
        ("Click “Add folder” to add music from your PC.", "Kattints a „Mappa hozzáadása” gombra, hogy zenét adj hozzá a gépedről."),
        ("No results for “{0}”", "Nincs találat erre: „{0}”"),
        ("No playable audio found in your folders.", "Nem található lejátszható hang a mappáidban."),
        ("No folders added yet — click “Add folder”.", "Még nincs mappa hozzáadva — kattints a „Mappa hozzáadása” gombra."),
        ("{0} folder", "{0} mappa"),
        ("{0} folders", "{0} mappa"),
        ("Scanning your music…", "A zenéd átvizsgálása…"),
        ("This playlist is empty — right-click songs in Local Music to add them.", "Ez a lejátszási lista üres — kattints jobb gombbal a dalokra a Helyi zenében a hozzáadáshoz."),
        ("PLAYLIST · ON THIS PC", "LEJÁTSZÁSI LISTA · EZEN A GÉPEN"),
        ("New playlist", "Új lejátszási lista"),
        ("Playlist name:", "Lejátszási lista neve:"),
        ("New Playlist", "Új lejátszási lista"),
        ("Created playlist “{0}” with {1} song(s).", "„{0}” lejátszási lista létrehozva {1} dallal."),
        ("Created playlist “{0}”.", "„{0}” lejátszási lista létrehozva."),
        ("Already in “{0}”.", "Már szerepel itt: „{0}”."),
        ("Added {0} song(s) to “{1}”.", "{0} dal hozzáadva ehhez: „{1}”."),
        ("Rename playlist", "Lejátszási lista átnevezése"),
        ("New name:", "Új név:"),
        ("Renamed playlist to “{0}”.", "A lejátszási lista átnevezve erre: „{0}”."),
        ("Delete the playlist “{0}”?\n\nThis only removes the playlist — your music files on the PC are untouched.", "Törlöd a(z) „{0}” lejátszási listát?\n\nEz csak a lejátszási listát távolítja el — a gépeden lévő zenefájlok érintetlenek maradnak."),
        ("Delete playlist", "Lejátszási lista törlése"),
        ("Deleted playlist “{0}”.", "„{0}” lejátszási lista törölve."),
        ("Removed {0} song(s) from “{1}”.", "{0} dal eltávolítva innen: „{1}”."),
        ("Add to playlist", "Hozzáadás lejátszási listához"),
        ("Remove from “{0}”   ({1})", "Eltávolítás innen: „{0}”   ({1})"),
        ("Choose a folder of music on your PC", "Válassz egy zenei mappát a gépeden"),
        ("Add folder…", "Mappa hozzáadása…"),
        ("Remove:  {0}", "Eltávolítás:  {0}"),
        ("Clear all folders", "Összes mappa törlése"),
        ("Drop to add to Local Music", "Húzd ide a Helyi zenéhez adáshoz"),
        ("Drop to add to your iPod", "Húzd ide az iPodhoz adáshoz"),
        ("Connect a writable iPod, or open Local Music, to add files by dropping them.", "Csatlakoztass egy írható iPodot, vagy nyisd meg a Helyi zenét, hogy fájlokat adj hozzá behúzással."),
        ("Drop music, video, or photo files — or a folder of them — to add them.", "Húzz ide zenét, videót vagy fényképfájlokat — vagy egy mappányit belőlük —, hogy hozzáadd őket."),
        ("That folder is already in your Local Music.", "Ez a mappa már a Helyi zenédben van."),
        ("Drop a music folder — or songs — to add them to Local Music.", "Húzz ide egy zenei mappát — vagy dalokat —, hogy hozzáadd őket a Helyi zenéhez."),
        ("Added a folder to Local Music.", "Egy mappa hozzáadva a Helyi zenéhez."),
        ("Added {0} folders to Local Music.", "{0} mappa hozzáadva a Helyi zenéhez."),
        ("Select video to copy onto the iPod", "Válassz videót az iPodra másoláshoz"),
        ("Video files", "Videófájlok"),
        ("ffmpeg was not found, so videos can't be converted to an iPod-compatible format.\n\n• Install ffmpeg (e.g. `winget install Gyan.FFmpeg`) and it'll be picked up automatically, or set its path in Settings ▸ Video.\n\nCopy the selected file(s) as-is for now? They will only play if they are already iPod-compatible H.264/MPEG-4.", "Az ffmpeg nem található, így a videók nem alakíthatók iPod-kompatibilis formátumra.\n\n• Telepítsd az ffmpeg-et (pl. `winget install Gyan.FFmpeg`), és automatikusan felismeri, vagy add meg az útvonalát a Beállítások ▸ Videó alatt.\n\nMost átmásolod a kijelölt fájl(oka)t úgy, ahogy van? Csak akkor játszhatók le, ha már iPod-kompatibilis H.264/MPEG-4 formátumúak."),
        ("Adding video to your iPod", "Videó hozzáadása az iPodhoz"),
        ("Processing {0} of {1}   ·   {2}", "Feldolgozás: {0}/{1}   ·   {2}"),
        ("not an iPod-compatible container — install ffmpeg to convert it.", "nem iPod-kompatibilis tároló — telepítsd az ffmpeg-et az átalakításához."),
        ("Stopped — added {0} video(s).", "Leállítva — {0} videó hozzáadva."),
        ("Added {0} video(s).", "{0} videó hozzáadva."),
        ("Select photos to copy onto the iPod", "Válassz fényképeket az iPodra másoláshoz"),
        ("Image files", "Képfájlok"),
        ("Adding photos to your iPod", "Fényképek hozzáadása az iPodhoz"),
        ("Rendering {0} of {1}   ·   {2}", "Megjelenítés: {0}/{1}   ·   {2}"),
        ("Saving… ({0} added so far)", "Mentés… (eddig {0} hozzáadva)"),
        ("Writing the photo library… (this can take a moment)", "A fénykép-könyvtár írása… (ez eltarthat egy ideig)"),
        ("Writing the photo library failed (a backup was kept as Photo Database.bak):\n\n{0}", "A fénykép-könyvtár írása sikertelen (biztonsági mentés megmaradt Photo Database.bak néven):\n\n{0}"),
        ("Stopped — added {0} photo(s).", "Leállítva — {0} fénykép hozzáadva."),
        ("Added {0} photo(s).", "{0} fénykép hozzáadva."),
        ("Select one or more photos to delete.", "Válassz ki egy vagy több fényképet a törléshez."),
        ("Delete {0} photo(s) from the iPod?\n\nA backup of the photo database is kept (Photo Database.bak).", "Törölsz {0} fényképet az iPodról?\n\nA fénykép-adatbázisról biztonsági mentés készül (Photo Database.bak)."),
        ("Delete photos", "Fényképek törlése"),
        ("Updating the photo library", "A fénykép-könyvtár frissítése"),
        ("Removing photos and repacking…", "Fényképek eltávolítása és újracsomagolás…"),
        ("Deleted {0} photo(s).", "{0} fénykép törölve."),
        ("View", "Megtekintés"),
        ("Delete {0} photo(s) from iPod", "{0} fénykép törlése az iPodról"),
        ("Rename…", "Átnevezés…"),
        ("Play video", "Videó lejátszása"),
        ("Copy to PC…   ({0})", "Másolás a gépre…   ({0})"),
        ("Edit {0} songs…", "{0} dal szerkesztése…"),
        ("Edit info…", "Adatok szerkesztése…"),
        ("Delete from iPod   ({0})", "Törlés az iPodról   ({0})"),
        ("Delete playlist (keep songs)", "Lejátszási lista törlése (dalok megtartása)"),
        ("Delete the playlist “{0}”?\n\nThe songs stay on the iPod — only the playlist itself is removed.", "Törlöd a(z) „{0}” lejátszási listát?\n\nA dalok az iPodon maradnak — csak maga a lejátszási lista törlődik."),
        ("Write failed (backup kept as iTunesDB.bak):\n\n{0}", "Az írás sikertelen (biztonsági mentés megmaradt iTunesDB.bak néven):\n\n{0}"),
        ("Deleted playlist “{0}” — songs kept.", "„{0}” lejátszási lista törölve — a dalok megmaradtak."),
        ("All selected songs are already in “{0}”.", "Minden kijelölt dal már szerepel itt: „{0}”."),
        ("Removed {0} song(s) from the playlist.", "{0} dal eltávolítva a lejátszási listából."),
        ("This playlist can't be edited — it has no stable identifier in the iPod's database, so nothing was changed.\n\n(Playlists you create in Mixtape don't have this limitation.)", "Ez a lejátszási lista nem szerkeszthető — nincs stabil azonosítója az iPod adatbázisában, így semmi sem változott.\n\n(A Mixtape-ben létrehozott lejátszási listákra ez a korlátozás nem vonatkozik.)"),
        ("Play an audio file from your PC", "Hangfájl lejátszása a gépedről"),
        ("Couldn't play that file:\n\n{0}", "Nem sikerült lejátszani azt a fájlt:\n\n{0}"),
        ("Play file", "Fájl lejátszása"),
        ("While reading your iPod's database, Mixtape noticed the following. These are non-fatal — your music still reads and plays normally:\n\n• ", "Az iPod adatbázisának olvasása közben a Mixtape a következőket vette észre. Ezek nem végzetesek — a zenéd továbbra is normálisan beolvasható és lejátszható:\n\n• "),
        ("\n\n(These usually come from how a previous app or sync wrote the database, and are safe to ignore.)", "\n\n(Ezek általában abból erednek, ahogy egy korábbi alkalmazás vagy szinkronizálás írta az adatbázist, és nyugodtan figyelmen kívül hagyhatók.)"),
        ("Database notes", "Adatbázis-megjegyzések"),
        ("the iPod", "az iPod"),
        ("Mixtape backs up the database (iTunesDB.bak) before every write and verifies the result afterwards.\n\nTip: if Windows has flagged this iPod's drive for repair, run  chkdsk {0} /f  first.\n\nContinue?", "A Mixtape minden írás előtt biztonsági mentést készít az adatbázisról (iTunesDB.bak), és utána ellenőrzi az eredményt.\n\nTipp: ha a Windows javításra jelölte ennek az iPodnak a meghajtóját, először futtasd a  chkdsk {0} /f  parancsot.\n\nFolytatod?"),
        ("Writing to the iPod", "Írás az iPodra"),
        ("Photo {0}", "{0}. fénykép"),
        ("Edit {0} songs", "{0} dal szerkesztése"),
        ("Song info", "Daladatok"),
        ("Editing {0} songs. Type in a field to set it on all of them; leave a field blank to keep each song's own value.", "{0} dal szerkesztése. Írj egy mezőbe, hogy mindegyikre beállítsd; hagyd üresen a mezőt, hogy minden dal megtartsa a saját értékét."),
        ("Title", "Cím"),
        ("(varies — not changed)", "(eltérő — nem módosul)"),
        ("Artist", "Előadó"),
        ("Album", "Album"),
        ("Album artist", "Album előadója"),
        ("Genre", "Műfaj"),
        ("Year", "Év"),
        ("Track #", "Szám #"),
        ("Rating", "Értékelés"),
        ("Save", "Mentés"),
        ("Cancel", "Mégse"),
        ("Use cover", "Borító használata"),
        ("Cancel", "Mégse"),
        ("Default", "Alapértelmezett"),
        ("Library Doctor", "Könyvtár doktor"),
        ("{0} songs and {1} photos", "{0} dal és {1} fénykép"),
        ("{0} songs", "{0} dal"),
        ("Scanned {0} — everything looks healthy.", "{0} átvizsgálva — minden rendben van."),
        ("Scanned {0}. Tick what you'd like Mixtape to tidy up:", "{0} átvizsgálva. Jelöld be, mit takarítson ki a Mixtape:"),
        ("Your library and the files on the iPod are consistent — no missing files, no duplicates, no stray files.", "A könyvtárad és az iPodon lévő fájlok összhangban vannak — nincs hiányzó fájl, nincs duplikátum, nincs elárvult fájl."),
        ("✓  No problems found", "✓  Nem találtunk problémát"),
        ("Missing files", "Hiányzó fájlok"),
        ("{0} song(s) point to a file that's no longer on the iPod. Remove these dead entries.", "{0} dal olyan fájlra mutat, amely már nincs az iPodon. Távolítsd el ezeket a holt bejegyzéseket."),
        ("Duplicates", "Duplikátumok"),
        ("{0} duplicate copy(ies) across {1} song(s). Delete the extras, keeping the best copy of each.", "{0} duplikált másolat {1} dalban. Töröld a feleslegeseket, megtartva mindegyik legjobb példányát."),
        ("Duplicate photos", "Duplikált fényképek"),
        ("{0} duplicate photo(s) across {1} set(s). Remove the extra copies, keeping one of each.", "{0} duplikált fénykép {1} csoportban. Távolítsd el a felesleges másolatokat, megtartva mindegyikből egyet."),
        ("Stray files", "Elárvult fájlok"),
        ("{0} file(s) on the iPod ({1}) aren't in your library. Delete them to reclaim space.", "{0} fájl az iPodon ({1}) nincs a könyvtáradban. Töröld őket, hogy helyet szabadíts fel."),
        ("Incomplete tags", "Hiányos címkék"),
        ("{0} song(s) missing title/artist/album", "{0} dalból hiányzik a cím/előadó/album"),
        ("Possibly incomplete albums", "Esetleg hiányos albumok"),
        ("{0} album(s) with a track-number gap", "{0} album számsorrend-hézaggal"),
        ("These are shown for awareness — fix them with the upcoming tag editor.", "Ezeket tájékoztatásul mutatjuk — javítsd őket a hamarosan érkező címkeszerkesztővel."),
        ("Close", "Bezárás"),
        ("Cancel", "Mégse"),
        ("Apply fixes", "Javítások alkalmazása"),
        ("Equalizer", "Hangszínszabályzó"),
        ("Flat", "Lapos"),
        ("Bass", "Mély"),
        ("Treble", "Magas"),
        ("Vocal", "Ének"),
        ("Rock", "Rock"),
        ("Pop", "Pop"),
        ("Pro Features", "Pro funkciók"),
        ("Off", "Ki"),
        ("Gapless playback", "Szünetmentes lejátszás"),
        ("No silence between back-to-back tracks", "Nincs csend az egymás utáni számok között"),
        ("Crossfade", "Áttűnés"),
        ("Blend the end of one track into the next", "Az egyik szám vége átúszik a következőbe"),
        ("Crossfade length", "Áttűnés hossza"),
        ("Volume normalization", "Hangerő-normalizálás"),
        ("Even out loud and quiet tracks", "Kiegyenlíti a hangos és halk számokat"),
        ("Mono", "Mono"),
        ("Combine left and right into one channel", "A bal és jobb csatornát egybe vonja"),
        ("Sleep timer", "Elalvásidőzítő"),
        ("Fade out and pause", "Lehalkít és szüneteltet"),
        ("Video", "Videó"),
        ("Photo", "Fénykép"),
        ("This photo can't be previewed.", "Ezt a fényképet nem lehet megjeleníteni."),
        ("Cancel", "Mégse"),
        ("Preparing…", "Előkészítés…"),
        ("Finishing the current file…", "Az aktuális fájl befejezése…"),
        ("Up Next", "Következik"),
        ("Clear", "Törlés"),
        ("NOW PLAYING", "MOST SZÓL"),
        ("Nothing queued.\nRight-click songs → “Add to queue”.", "Nincs a sorban semmi.\nKattints jobb gombbal a dalokra → „Hozzáadás a sorhoz”."),
        ("Drop to add", "Húzd ide a hozzáadáshoz"),
        ("Release to add them", "Engedd el a hozzáadáshoz"),
        ("free of {0}", "szabad / {0}"),
        ("Songs", "Dalok"),
        ("Albums", "Albumok"),
        ("Artists", "Előadók"),
        ("Now Playing", "Most szól"),
        ("Equalizer…", "Hangszínszabályzó…"),
        ("Pro features…", "Pro funkciók…"),
        ("Show full window", "Teljes ablak megjelenítése"),
    };
}
